### ISSUE TITLE
Show number of guesses 

### ISSUE THREAD

**Issue by TalUser** [ishefi/semantle-he#20]
Show the number of the last guess (how many guesses so far)

**Comment by ishefi** [comment]
The first number that in every guess row is the number of the guess. This applies to the last guess as well

**Comment by TalUser** [comment]
OK. But keep in mind that many times the last guesd is deep down in the list due to its low proximity, making it hard to find quickly

**Comment by TalUser** [comment]
OK. But keep in mind that many times the last guesd is deep down in the list due to its low proximity, making it hard to find quickly

**Comment by ishefi** [comment]
This should be solved by #15
