### ISSUE TITLE
Negative similarity score

### ISSUE THREAD

**Issue by eliyahillel** [ishefi/semantle-he#21]
![image](https://user-images.githubusercontent.com/73447394/159140573-ea16254d-073c-4e2e-8d08-641f01be4578.png)
🤷‍♂️

**Comment by ishefi** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/11841271/159158151-33fb4ce2-ec13-4403-8239-c534ccf8d9ee.png">
🤷
