### ISSUE TITLE
Change refresh time

### ISSUE THREAD

**Issue by Elinor10** [ishefi/semantle-he#27]
The game used to refresh (new secret word) at 2:00am (Israel time, GMT‎+3). 
Since the switch to DST (Daylight Saving Time / שעון קיץ) it now refreshes at 3:00am.
If possible (and accepted) - I suggest to change the refresh time to midnight - 12:00am (along with all Wordle variations) or at least back to 2:00am.

**Comment by ishefi** [comment]
This is intended - see [game's FAQ](https://semantle-he.herokuapp.com/faq)
