### ISSUE TITLE
Generating the word2vec db

### ISSUE THREAD

**Issue by alonstern** [ishefi/semantle-he#28]
Hi,
Could you provide more detailed instructions on how to generate the word2vec db? E.g., at what part and how to use the [HebPipe](https://github.com/amir-zeldes/HebPipe) you mentioned in the faq.
Thanks

**Comment by ishefi** [comment]
This is what we do for the w2v model - [https://github.com/Iddoyadlin/hebrew-w2v](https://github.com/Iddoyadlin/hebrew-w2v)

Once you have a model you can use `scripts/populate.py` in order to populate the db.
