### ISSUE TITLE
Share to telegram with spoiler

### ISSUE THREAD

**Issue by omertal323** [ishefi/semantle-he#29]
It'll be nice to share my solve story with the actuall guesses I tried, to avoid spoilers, the "spoiler" markdown in telegram can be used. Since this feature avaible only on telegram, a seperate share button should be added.

The message should look like this:
![image](https://user-images.githubusercontent.com/68015426/160276040-b0f9b058-658e-4ad5-8f0f-5bd18c735d96.png)

and after clicking a spoiler:
![image](https://user-images.githubusercontent.com/68015426/160276059-3e131edc-f421-48fa-8e55-ac8373ba8564.png)

telegram mardown for spoiler is leading and trailing '||'

**Comment by ishefi** [comment]
The share should be cross-platform. I don't think it's a good idea to create multiple sharing options for different platforms.

In addition, I'm generally against spoilers for סמנטעל; and I don't want to make it easy to share them :)
