### ISSUE TITLE
Rules page appears below the videos in the videos page

### ISSUE THREAD

**Issue by talbz** [ishefi/semantle-he#34]
When clicking the question mark on the videos page, the rules \<div> appears below the video \<div>. One possible solution is to add **position** and **z-index** to both elements, the video \<div> and the rules \<div>.

<img width="926" alt="image" src="https://user-images.githubusercontent.com/34829710/162589523-3e2d52da-d203-4f68-a528-aa0962876ced.png">

**Comment by Iddoyadlin** [comment]
@talbz would you like to create a PR?

**Comment by talbz** [comment]
will do

**Comment by Iddoyadlin** [comment]
@ishefi we're good here right? closing
