### ISSUE TITLE
Phrases with more than one word are never accepted

### ISSUE THREAD

**Issue by NeatNit** [ishefi/semantle-he#38]
The How To Play page says that a guess can be "מילה או ביטוי קצר". To date, I have not found a guess with more than one word that was accepted. Examples: ראש ממשלה, עמוד שדרה, קרוב משפחה.

I haven't looked at the code but I suspect there is no mechanism to ever add these kinds of words to the database. In that case, the How To Play text should be updated.

**Comment by Iddoyadlin** [comment]
sounds like you're right. can you create a PR with an alternative phrasing?

**Comment by ishefi** [comment]
Closing, as #39 is preferred
