### ISSUE TITLE
Augment data using english language

### ISSUE THREAD

**Issue by adic0hen** [ishefi/semantle-he#40]
Just a thought about how you can improve the precision and make your model better understand semantic relationship between words. Why not just use english? Then you can just add a layer of tramslation before generating the embedding of each guess. Assuming that hebrew to english translation is reliable, you'll be able to benefit from the abundance of work that has been done on english word2bec or any other word embedding technique. :)

**Comment by Iddoyadlin** [comment]
You can do something like this and show us that it actually improves the embedding. if we're convinced, we might add it to our model.
