### ISSUE TITLE
Missing word

### ISSUE THREAD

**Issue by DrBamba** [ishefi/semantle-he#43]
המשחק אמר שהוא לא מכיר את המילה וניל, מנחש שאולי היא פורקה ל ו+ניל
בויקיפדיה מילים כתובות עם ניקוד אם אני לא טועה אז אפשר לקחת את זה בחשבון או בתהליך הפירוק של המילים או בכללי

**Comment by ishefi** [comment]
You _are_ wrong, most words in Wikipedia do not have ניקוד. 

In any case, the code of the model is available here: https://github.com/Iddoyadlin/hebrew-w2v

If you have a concrete (and proven) solution you are welcome to suggest it there.
