### ISSUE TITLE
Add positional encodings for better consistency?

### ISSUE THREAD

**Issue by Sagivfer** [ishefi/semantle-he#45]
Something like they did in BERT. In the standard gensim Word2Vec they don't take into considerations order of the sentence.
Adding positional encodings maybe can improve consistency by giving some weight to order.

**Comment by Iddoyadlin** [comment]
@Sagivfer If you'd like to help improve the model, take a look at the readme that points to a repo that allows reproducing the entire training process +data+similar model. 
we'll be happy to hear suggestions, but we'll be even happier to see actual pull requests/models that convince us that your suggestion indeed improves on the current model
