### ISSUE TITLE
Use a different data set, other than the Israeli Wikipedia?

### ISSUE THREAD

**Issue by Eitheladar** [ishefi/semantle-he#48]
Israeli Wikipedia is very uneven in its coverage of words. Is it the best freely-available Hebrew data set out there? What about ynet news archive, for example?

**Comment by ishefi** [comment]
Suggestions for the language model should go here - https://github.com/Iddoyadlin/hebrew-w2v

Also, please provide a concrete way to do so + proofs that it is indeed better. Wikipedia as a corpus is available to download, I don't know of any news corpus which is available to download as plain text.
